app/flask_steam/blueprints/favorite/models.py
from ext.database import db


class Game(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    steam_id = db.Column(db.Integer, unique=True, nullable=False)
    name = db.Column(db.String(150), nullable=False)
    logo_url = db.Column(db.String(255), nullable=False)

    def __repr__(self):
        return '<Game %r>' % self.steam_id

app/flask_steam/blueprints/favorite/__init__.py
from flask import Blueprint

from .views import index, game, save_favorite, delete_favorite, search_values, steam_list


favorite_bp = Blueprint("favorite", __name__, template_folder="templates")

favorite_bp.add_url_rule("/", view_func=index)
favorite_bp.add_url_rule(
    "/game/<string:game_id>", view_func=game, endpoint="game"
)
favorite_bp.add_url_rule(
    "/save-favorite/", view_func=save_favorite, endpoint="save_favorite", methods=['POST',]
)
favorite_bp.add_url_rule(
    "/delete-favorite/", view_func=delete_favorite, endpoint="delete_favorite", 
    methods=['POST',]
)
favorite_bp.add_url_rule(
    "/search-values/", view_func=search_values, endpoint="search_values"
)
favorite_bp.add_url_rule(
    "/steam-list/", view_func=steam_list, endpoint="steam_list"
)


def init_app(app):
    app.register_blueprint(favorite_bp)

app/flask_steam/blueprints/favorite/views.py
import json, locale

from flask import render_template, jsonify, url_for, redirect, request, flash
import requests

from ext.cache import cache
from blueprints.favorite.doa import delete_game, save_game, all_games, get_game


LINK_GAME_DETAILS = 'https://store.steampowered.com/api/appdetails?appids='

locale.setlocale(locale.LC_MONETARY, 'pt_BR.UTF-8')


def conversor_moeda(valor):
    moeda_convertida = requests.get('https://economia.awesomeapi.com.br/ARS-BRL/')
    moeda_convertida = json.loads(moeda_convertida.content)[0]['high']
    return locale.currency(
        float(moeda_convertida) * float(format(valor / 100, '.02f')), 
        grouping=True
    )

def busca_dados_steam(game_id):
    game_id_str = str(game_id)
    link = LINK_GAME_DETAILS + game_id

    # Busca dados do jogo no Brasil
    retorno = requests.get(link + '&cc=br&l=pt')
    json_retorno = json.loads(retorno.content)

    if json_retorno[game_id_str]['success'] == True:

        data_game = json_retorno[game_id_str]['data']
        preco_detalhes_br = data_game.get('price_overview', 0)

        # Busca dados na Argentina para buscar valor
        retorno_arg = requests.get(link + '&cc=ar')
        json_retorno_arg = json.loads(retorno_arg.content)

        if json_retorno_arg[game_id_str]['success'] == True:
            preco_detalhes_arg = json_retorno_arg[game_id_str]['data'].get('price_overview', 0)
        else:
            preco_detalhes_arg = 0

        # Converter moeda ARG para BRL
        if preco_detalhes_arg:
            moeda_hoje = conversor_moeda(preco_detalhes_arg['final'])
        else:
            moeda_hoje = 0

        return {
            'data_game': data_game,
            'preco_detalhes_br': preco_detalhes_br,
            'preco_detalhes_arg': preco_detalhes_arg,
            'moeda_hoje': moeda_hoje
        }

    else:
        return None


def index():
    """ Página principal """
    list_favorites = all_games()
    return render_template('index.html', list_favorites=list_favorites)

def game(game_id):
    """ Exibe detalhes do jogo """
    dados_steam = busca_dados_steam(game_id)

    if dados_steam:
        # Verifica se game esta salvo como favorito
        favorite = get_game(game_id)
        steam_id = favorite.steam_id if favorite else 0

        dados = {
            'id_game': game_id,
            'id_favorite': steam_id,
            'nome': dados_steam['data_game']['name'],
            'preco_detalhes': dados_steam['preco_detalhes_br'],
            'preco_detalhes_arg': dados_steam['preco_detalhes_arg'],
            'logo': dados_steam['data_game']['header_image'],
            'moeda_hoje': dados_steam['moeda_hoje']
        }
        return render_template('game_details.html', dados=dados)
    else:
        return render_template('404.html', title = '404'), 404
    

def save_favorite():
    """ Salva o jogo como favorito"""
    save_game(request.form)
    flash('Salvo com sucesso!')
    return redirect(url_for('favorite.index'))

def delete_favorite():
    """ Deleta favorito """
    delete_game(request.form['steam_id'])
    flash('Removido com sucesso!')
    return redirect(url_for('favorite.index'))


def search_values():
    """ Busca valores atualizados dos games favoritados """
    all_favorites = all_games()
    games_list = []

    for favorite in all_favorites:
        steam_id_string = str(favorite.steam_id)
        game_dict = {}

        dados_steam = busca_dados_steam(steam_id_string)

        if dados_steam:
            game_dict['id'] = steam_id_string
            game_dict['brl'] =  dados_steam['preco_detalhes_br']['final_formatted']
            game_dict['arg'] =  dados_steam['preco_detalhes_arg']['final_formatted']

            game_dict['conversao'] = conversor_moeda(dados_steam['preco_detalhes_arg']['final'])
            games_list.append(game_dict)

    
    return jsonify(games_list)



@cache.cached(timeout=86400, key_prefix="steam_list")
def steam_list():

    """ Lista jogos da steam """
    retorno = requests.get(
        'https://api.steampowered.com/ISteamApps/GetAppList/v2/'
    )
    json_retorno = json.loads(retorno.content)
    data_game = json_retorno['applist']['apps']

    return jsonify(data_game)

app/flask_steam/blueprints/favorite/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <title>{{ config.get('TITLE') }}</title>
   <!--Import Google Icon Font-->
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  <!-- Ajax -->
        
</head>
<body>

  <nav>
    <div class="nav-wrapper {{ config.get('THEME') }} accent-3">
      <a href="{{ url_for('favorite.index') }}" class="brand-logo" style="margin-left:15px">{{ config.get('TITLE') }}</a>
    </div>
  </nav>

<div class="container">
{% block content %}
{% endblock %}
</div>

</body>


{% block js %}
{% endblock %}

</html>

app/flask_steam/blueprints/favorite/templates/game_details.html
{% extends 'base.html' %}

{% block content %}

<div class="row">

    <table class="table">
        <thead>
            <tr>
                <td>
                    <p class="flow-text">{{ dados.nome }}</hp>
                </td>
            </tr>
            <tr>
                <td><img src="{{ dados.logo }}"></td>
            </tr>
        </thead>
        <tbody>
            {% if dados.preco_detalhes != 0 %}
            <tr class="highlight">
                <th>Moeda</th>
                <td>{{ dados.preco_detalhes.currency }}</td>
                <td>{{ dados.preco_detalhes_arg.currency }}</td>
            </tr>
            <tr class="highlight">
                <th>Preço anterior</th>
                <td>{{ dados.preco_detalhes.initial_formatted }}</td>
                <td>{{ dados.preco_detalhes_arg.initial_formatted }}</td>
            </tr>
            <tr class="highlight">
                <th>Desconto</th>
                <td>{{ dados.preco_detalhes.discount_percent }}%</td>
                <td>{{ dados.preco_detalhes_arg.discount_percent }}%</td>
            </tr>
            <tr class="highlight">
                <th>Preço atual</th>
                <td>{{ dados.preco_detalhes.final_formatted }}</td>
                <td>{{ dados.preco_detalhes_arg.final_formatted }}</td>
            </tr>
            <tr class="highlight">
                <th>Preço em reais</th>
                <td>-</td>
                <td>{{ dados.moeda_hoje }}</td>
            </tr>
            {% else %}
            <tr class="highlight">
                <th>Valores não disponíveis para mais detalhes acesse:</th>
                <td>
                    <a href="https://store.steampowered.com/agecheck/app/{{ dados.id_game }}/" target="_blank">
                        https://store.steampowered.com/agecheck/app/{{ dados.id_game }}
                    </a>
                </td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <p> 
        
    {% if dados.id_favorite %}
    <form action="{{ url_for('favorite.delete_favorite') }}" method="post" >
        <input name="steam_id" type="hidden" value="{{ dados.id_game }}">
        <button class="waves-effect waves-light btn red accent-3" type="submit">Deletar favorito</button>
    </form>

    {% elif dados.preco_detalhes %}
        <form action="{{ url_for('favorite.save_favorite') }}" method="post" >
            <input name="steam_id" type="hidden" value="{{ dados.id_game }}">
            <input name="name" type="hidden" value="{{ dados.nome }}">
            <input name="logo_url" type="hidden" value="{{ dados.logo }}">
            <button class="waves-effect waves-light btn" type="submit">Salvar favorito</button>
        </form>
 
    {% endif %}
        
    </p>

</div>

{% endblock %}

app/flask_steam/blueprints/favorite/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row m 8">
    <div class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">search</i>
          <input type="text" id="autocomplete-input" class="autocomplete">
          <label for="autocomplete-input">Informe Nome do jogo ou ID Steam</label>
        </div>
      </div>
    </div>
  </div>

{% include 'list.html' %}

{% endblock %}

{% block js %}

{% with messages = get_flashed_messages() %}
{% if messages %}
    {% for message in messages %}
    <script>
      M.toast({html: '{{ message }}'})
    </script>
    {% endfor %}
{% endif %}
{% endwith %}


<script>

function search_values(){
  // Exibe valores dos jogos na Steam Argentina e Brasil

  $('.progress').show();
  let percent = 0;

  $.ajax({
    type: 'GET',
    url: "{{ url_for('favorite.search_values') }}",
    success: response => {

      favorites = response.length;

      for (var i = 0; i < favorites; i++) {

        const data = `
                <p><b>Preço BRL:</b> ${response[i].brl}</p>
                <p><b>Preço ARS:</b> ${response[i].arg}</p>
                <p><b>Preço convertido:</b> ${response[i].conversao}</p>
                `
        const elem = $('#' + response[i].id);

        if(elem.length){
          percent += (1 / favorites) * 100;
          $('.determinate').attr('style',`width: ${percent}%`);
          elem.html(data);
        }

      }

      setTimeout(function(){ 
        $('.progress').hide();
        $('.determinate').attr('style','width: 0%');
      }, 1000);


    },
    error: function(error){
      console.log(error);
      M.toast({html: 'Erro ao buscar dados !'})
    }
  });
}


$(document).ready(function() {

    // Busca lista de jogos steam para autocomplete
    $.ajax({
      type: 'GET',
      url: "{{ url_for('favorite.steam_list') }}",
      success: function(response) {

        var gameArray = response;
        var dataGame = {};

        for (var i = 0; i < gameArray.length; i++) {
          dataGame[
            gameArray[i].name + ' (' + gameArray[i].appid +')'
            ] = null; // define imagem como null
        }
        
        $('input.autocomplete').autocomplete({
            data: dataGame,
            limit: 30,
            minLength: 3,
            onAutocomplete: function (val) {

                //Pega id da string
                var newTxt = val.split('(');
                for (var i = 1; i < newTxt.length; i++) {
                    game_id = newTxt[i].split(')')[0];
                }

                link = "{{ url_for('favorite.game', game_id=0) }}";
                new_link = link.replace(0, game_id);
                window.location.href = new_link;
            },
        },

        );
        
      }
    });
    
});
</script>
{% endblock %}

app/flask_steam/blueprints/favorite/templates/list.html
<p class="col s4 " title="Buscar valores na API da Steam">
    <a class="waves-effect waves-light btn right" onclick="search_values()">Exibe valores</a>
</p>

<h4>Favoritos </h4>

<div class="progress" style="display: none;">
    <div class="determinate" style="width: 0%"></div>
</div>

{% for favorite in list_favorites %}

<div class="divider"></div>
<div class="section">
    <h5>{{ favorite.name }}</h5>

    <div class="row">
        <a href="{{ url_for('favorite.game', game_id=favorite.steam_id) }}">
            <img class="col s4" src="{{ favorite.logo_url }}">
        </a>
        
        <div id="{{ favorite.steam_id }}"></div>
        <form class="right" action="{{ url_for('favorite.delete_favorite') }}" method="post" >
            <input name="steam_id" type="hidden" value="{{ favorite.steam_id }}">
            <button class="waves-effect waves-light btn red accent-3" type="submit">Excluir</button>
        </form>
    </div>

    {% endfor %}
    <div class="divider"></div>

</div>

{% if not list_favorites %}
<div class="container">
    <p>Nenhum favorito cadastrado</p>
</div>
{% endif %}